In [1]:
"hello"

'hello'

In [5]:
import numpy as np

In [6]:
from scipy import stats
rng = np.random.default_rng()

In [7]:
sample1 = stats.uniform.rvs(size=100, random_state=rng)


In [9]:
sample1

array([0.03239395, 0.84129621, 0.45432404, 0.89265332, 0.73049085,
       0.55572976, 0.5094387 , 0.9897458 , 0.89154594, 0.35147639,
       0.74995518, 0.97202195, 0.40679628, 0.16496306, 0.290762  ,
       0.83367124, 0.47096207, 0.89733791, 0.24119991, 0.415413  ,
       0.26387099, 0.52042857, 0.90028129, 0.47224076, 0.74071401,
       0.25883092, 0.84992634, 0.40997606, 0.61118829, 0.66835131,
       0.89190236, 0.61868462, 0.10312292, 0.7878956 , 0.35385434,
       0.1301426 , 0.79936877, 0.54989996, 0.25629852, 0.69871112,
       0.43381906, 0.82617692, 0.70436531, 0.31744776, 0.35695744,
       0.38639106, 0.64316667, 0.71527347, 0.11541348, 0.15032349,
       0.02035125, 0.35075558, 0.88597714, 0.21993163, 0.744319  ,
       0.44493139, 0.9543471 , 0.64558506, 0.47978121, 0.07983434,
       0.80152353, 0.28857583, 0.14446923, 0.26205534, 0.13624762,
       0.93637357, 0.39407886, 0.95602577, 0.15361857, 0.79622722,
       0.619294  , 0.81806102, 0.87722121, 0.76394068, 0.61625

In [8]:
sample2 = stats.norm.rvs(size=110, random_state=rng)


In [10]:
sample2

array([ 0.40594066, -0.03811755, -0.89006658, -0.93940771, -0.23141783,
        0.57169113, -0.88111868,  0.3509249 ,  0.03521949, -1.02433663,
       -0.87771313,  1.15496284, -0.07152887,  1.31920031,  1.85840126,
        0.2760576 , -1.42953563, -0.63175199,  1.71380898, -1.11629757,
       -1.02131477,  0.75318083,  0.08834485, -0.20503285,  0.48244655,
        0.54854814, -0.2854829 ,  1.30663134,  0.01343454,  0.44689513,
       -0.34408328, -0.46933715, -0.03450429,  0.45895057, -0.29433348,
       -0.30914886,  0.47599524,  0.3381844 ,  0.47861985, -0.113602  ,
        0.58911872,  0.44059172, -0.58256738, -0.59974158,  0.80536885,
        0.44648413,  0.11272391, -0.90271074,  1.67037986, -0.20427224,
        1.41930981, -0.84550964,  0.61066797, -0.75626095,  0.15050827,
        0.10026075,  1.36227177,  0.90276531,  0.64327733,  1.17687953,
       -1.08668191,  0.3781216 , -0.65846821,  1.67988561, -1.23762545,
        0.58205242, -0.02027079,  0.2747354 ,  0.19297979,  0.82

In [13]:
response = stats.ks_2samp(sample1, sample2)

In [16]:
response

KstestResult(statistic=0.5272727272727272, pvalue=7.26220122467953e-14)

In [14]:
response.pvalue

7.26220122467953e-14

# #Anomly in Dataset
# 1. Missing Values
# 2. Outlier
# Categorical:
     Gender ---> Male, Female, Others


In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/config/workspace/aps_failure_training_set1.csv")

In [3]:
df.isnull().sum()

class     0
aa_000    0
ab_000    0
ac_000    0
ad_000    0
         ..
ee_007    0
ee_008    0
ee_009    0
ef_000    0
eg_000    0
Length: 171, dtype: int64

In [4]:
df1 = pd.read_csv("/config/workspace/artifact/12112022__013942/data_ingestion/dataset/train.csv")

In [5]:
df1.isnull().sum()

class         0
aa_000        0
ab_000    22354
ac_000     1709
ad_000     7369
          ...  
ee_007      315
ee_008      315
ee_009      315
ef_000     1380
eg_000     1379
Length: 171, dtype: int64

In [7]:
df1.shape

(28950, 171)

In [8]:
df1.isnull().sum()/df1.shape[0]

class     0.000000
aa_000    0.000000
ab_000    0.772159
ac_000    0.059033
ad_000    0.254542
            ...   
ee_007    0.010881
ee_008    0.010881
ee_009    0.010881
ef_000    0.047668
eg_000    0.047634
Length: 171, dtype: float64

In [11]:
(df1.isnull().sum()/df1.shape[0]).values

array([0.        , 0.        , 0.77215889, 0.05903282, 0.25454231,
       0.0435924 , 0.0435924 , 0.01088083, 0.01088083, 0.01088083,
       0.01088083, 0.01088083, 0.01088083, 0.01088083, 0.01088083,
       0.01088083, 0.01088083, 0.01088083, 0.01067358, 0.01067358,
       0.07709845, 0.01084629, 0.01067358, 0.01084629, 0.00991364,
       0.01084629, 0.00991364, 0.04763385, 0.01067358, 0.01067358,
       0.01067358, 0.04362694, 0.04366149, 0.01088083, 0.01088083,
       0.01088083, 0.01088083, 0.01088083, 0.01088083, 0.01088083,
       0.01088083, 0.01088083, 0.01088083, 0.01088083, 0.01088083,
       0.01088083, 0.01088083, 0.01088083, 0.01088083, 0.01088083,
       0.01088083, 0.01088083, 0.01088083, 0.01105354, 0.01105354,
       0.01105354, 0.01105354, 0.01105354, 0.01105354, 0.01105354,
       0.01105354, 0.01105354, 0.01105354, 0.01088083, 0.04766839,
       0.04770294, 0.04366149, 0.0435924 , 0.01084629, 0.01084629,
       0.00991364, 0.00991364, 0.38452504, 0.45329879, 0.65668

In [14]:
(df1.isnull().sum()/df1.shape[0]).values.__len__()

171

In [15]:
(df1.isnull().sum()/df1.shape[0]).index

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [17]:
for column_name, missing_percentage in zip((df1.isnull().sum()/df1.shape[0]).index, (df1.isnull().sum()/df1.shape[0]).values):
    print(column_name, missing_percentage*100)


class 0.0
aa_000 0.0
ab_000 77.21588946459413
ac_000 5.903281519861831
ad_000 25.454231433506045
ae_000 4.3592400690846285
af_000 4.3592400690846285
ag_000 1.0880829015544042
ag_001 1.0880829015544042
ag_002 1.0880829015544042
ag_003 1.0880829015544042
ag_004 1.0880829015544042
ag_005 1.0880829015544042
ag_006 1.0880829015544042
ag_007 1.0880829015544042
ag_008 1.0880829015544042
ag_009 1.0880829015544042
ah_000 1.0880829015544042
ai_000 1.067357512953368
aj_000 1.067357512953368
ak_000 7.709844559585492
al_000 1.0846286701208983
am_0 1.067357512953368
an_000 1.0846286701208983
ao_000 0.9913644214162348
ap_000 1.0846286701208983
aq_000 0.9913644214162348
ar_000 4.763385146804836
as_000 1.067357512953368
at_000 1.067357512953368
au_000 1.067357512953368
av_000 4.362694300518135
ax_000 4.366148531951641
ay_000 1.0880829015544042
ay_001 1.0880829015544042
ay_002 1.0880829015544042
ay_003 1.0880829015544042
ay_004 1.0880829015544042
ay_005 1.0880829015544042
ay_006 1.0880829015544042
ay_00

In [20]:
drop_columns_name=[]
for column_name, missing_percentage in zip((df1.isnull().sum()/df1.shape[0]).index, (df1.isnull().sum()/df1.shape[0]).values):
    print(column_name, missing_percentage*100)
    if missing_percentage > 0.3:
        drop_columns_name.append(column_name)
print(drop_columns_name)


class 0.0
aa_000 0.0
ab_000 77.21588946459413
ac_000 5.903281519861831
ad_000 25.454231433506045
ae_000 4.3592400690846285
af_000 4.3592400690846285
ag_000 1.0880829015544042
ag_001 1.0880829015544042
ag_002 1.0880829015544042
ag_003 1.0880829015544042
ag_004 1.0880829015544042
ag_005 1.0880829015544042
ag_006 1.0880829015544042
ag_007 1.0880829015544042
ag_008 1.0880829015544042
ag_009 1.0880829015544042
ah_000 1.0880829015544042
ai_000 1.067357512953368
aj_000 1.067357512953368
ak_000 7.709844559585492
al_000 1.0846286701208983
am_0 1.067357512953368
an_000 1.0846286701208983
ao_000 0.9913644214162348
ap_000 1.0846286701208983
aq_000 0.9913644214162348
ar_000 4.763385146804836
as_000 1.067357512953368
at_000 1.067357512953368
au_000 1.067357512953368
av_000 4.362694300518135
ax_000 4.366148531951641
ay_000 1.0880829015544042
ay_001 1.0880829015544042
ay_002 1.0880829015544042
ay_003 1.0880829015544042
ay_004 1.0880829015544042
ay_005 1.0880829015544042
ay_006 1.0880829015544042
ay_00

In [21]:
drop_columns_name=[]
for column_name, missing_percentage in zip((df1.isnull().sum()/df1.shape[0]).index, (df1.isnull().sum()/df1.shape[0]).values):
    if missing_percentage > 0.3:
        drop_columns_name.append(column_name)
print(drop_columns_name)

['ab_000', 'bk_000', 'bl_000', 'bm_000', 'bn_000', 'bo_000', 'bp_000', 'bq_000', 'br_000', 'cr_000']


In [25]:
null_report = df1.isna().sum()/df1.shape[0]

In [27]:
null_report[null_report>0.3].index

Index(['ab_000', 'bk_000', 'bl_000', 'bm_000', 'bn_000', 'bo_000', 'bp_000',
       'bq_000', 'br_000', 'cr_000'],
      dtype='object')

In [28]:
null_report = df1.isna().sum()/df1.shape[0]
null_report[null_report>0.3].index

Index(['ab_000', 'bk_000', 'bl_000', 'bm_000', 'bn_000', 'bo_000', 'bp_000',
       'bq_000', 'br_000', 'cr_000'],
      dtype='object')

In [29]:
df1.head()

class  aa_000  ab_000  ac_000  ad_000  ae_000  af_000  ag_000  ag_001  \
0   neg   38736     NaN  1022.0   934.0     0.0     0.0     0.0     0.0   
1   neg    1850     NaN   284.0   260.0     0.0     0.0     0.0     0.0   
2   neg   80420     NaN     0.0     NaN     0.0     0.0     0.0     0.0   
3   neg   60184     NaN   788.0     0.0     0.0     0.0     0.0     0.0   
4   neg      12     NaN    30.0    18.0     0.0     0.0     0.0     0.0   

   ag_002  ...    ee_002    ee_003    ee_004    ee_005    ee_006    ee_007  \
0     0.0  ...  586062.0  252174.0  330586.0  229704.0  104934.0   63802.0   
1     0.0  ...    7036.0    5358.0   21482.0   51320.0       6.0       0.0   
2     0.0  ...  808026.0  333080.0  611328.0  512818.0  429152.0  345960.0   
3     0.0  ...  607984.0  309842.0  673286.0  437348.0  219484.0  116112.0   
4     0.0  ...     298.0      20.0      28.0       6.0       0.0       0.0   

     ee_008   ee_009  ef_000  eg_000  
0  127320.0   6832.0     0.0     0.0  
1       0.0      0.0     0.0     0.0  
2  456106.0   5086.0     0.0     0.0  
3  183916.0  12114.0     0.0     0.0  
4       0.0      0.0     0.0     0.0  

[5 rows x 171 columns]

In [35]:
df1.iloc[:,[0]]

class
0       neg
1       neg
2       neg
3       neg
4       neg
...     ...
28945   neg
28946   neg
28947   neg
28948   neg
28949   neg

[28950 rows x 1 columns]

In [37]:
df1.iloc[:,[0]].drop("class",axis=1).columns

Index([], dtype='object')

In [38]:
len(df1.iloc[:,[0]].drop("class",axis=1).columns)

0

In [42]:
(df1.iloc[:,0]).__len__()

28950

In [43]:
(df1.iloc[:,[0]].drop("class",axis=1).columns).__len__()

0